from enum import StrEnum

class OperatingCategory(StrEnum):
    PRODUCTION_CONFIGURATION = "PRODUCTION_CONFIGURATION"
    LIVE_3COMMAS_CONFIGURATION = "LIVE_3COMMAS_CONFIGURATION"
    RESEARCH_CANDIDATE = "RESEARCH_CANDIDATE"
    FROZEN_CANDIDATE = "FROZEN_CANDIDATE"
    FORWARD_VALIDATED_CONFIGURATION = "FORWARD_VALIDATED_CONFIGURATION"
    DEPLOYMENT_RECOMMENDATION = "DEPLOYMENT_RECOMMENDATION"
